name: observatorio_secop
version: 1.0.0
config-version: 2

profile: observatorio_secop

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: target
clean-targets: ["target", "dbt_packages", "logs"]

models:
  observatorio_secop:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    dimensions:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +on_schema_change: fail
      +schema: analytics
    facts:
      +materialized: incremental
      +incremental_strategy: delete+insert
      +on_schema_change: fail
      +schema: analytics

vars:
  star_key_version: star_key_v1
