select
    silver_version_id,
    silver_manifest_sha256,
    loaded_at,
    contract_key,
    source_dataset_id,
    source_contract_id as contract_id,
    contract_reference,
    procurement_process_id as process_id,
    entity_name,
    municipality_name,
    municipality_key,
    municipality_status,
    procurement_method,
    signing_date,
    start_date,
    end_date,
    contract_value_cop,
    contract_status as status,
    source_url,
    source_updated_at,
    bronze_fetched_at_utc,
    payload_sha256
from {{ source('silver', 'contract_current') }}
